#pragma once

#include "nitro.h"

#include "nsmb/actor/actor.h"
#include "nsmb/actor/collider.h"
#include "nsmb/actor/nsmbtypes.h"
#include "nsmb/actor/physics.h"
#include "nsmb/actor/player.h"
#include "nsmb/actor/solidcollision.h"
#include "nsmb/bnbl.h"
#include "nsmb/bncl.h"
#include "nsmb/events.h"
#include "nsmb/fxmath.h"
#include "nsmb/heap.h"
#include "nsmb/misc.h"
#include "nsmb/model.h"
#include "nsmb/nfs.h"
#include "nsmb/nocashPrint.h"
#include "nsmb/oam.h"
#include "nsmb/ostream.hpp"
#include "nsmb/sound.h"
#include "nsmb/vector.h"